theme: jekyll-theme-cayman
title: Harry Ankcorn
description: Aspiring Data Engineer
show_downloads: true
github:
  zip_url: http://potato.com/download.zip
  LinkedIn: https://www.linkedin.com/in/harry-ankcorn/