theme: jekyll-theme-cayman
title: Harry Ankcorn
description: Aspiring Data Engineer
show_downloads: true
github:
  GitHub: https://github.com/HarryAnkcorn
  LinkedIn: https://www.linkedin.com/in/harry-ankcorn/